name: mercor_job_task_1
description: A web app that uses AngularDart Components
version: 0.0.1
# homepage: https://www.example.com

environment:
  sdk: '>=3.7.3'

dependencies:
  ngdart: ^8.0.0-dev.4
  ngforms: ^5.0.0-dev.3
  ngrouter: ^4.0.0-dev.3

dev_dependencies:
  meta: ^1.16.0
  ngtest: ^5.0.0-dev.3
  build_runner: ^2.2.0
  build_version: ^2.1.1
  build_test: ^2.1.5
  build_web_compilers: ^4.1.5
  lints: ^5.1.1
  test: ^1.21.0
